<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.0.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Cadastro Formulário envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'annaredistuo@gmail.com',
		'to' => 'annaredistuo@gmail.com'
	),
	'fields' => array(
		'custom_U1968' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'CPFou CNPJ',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"CPFou CNPJ\" é obrigatório.',
				'format' => 'O campo \"CPFou CNPJ\" possui um email inválido.'
			)
		),
		'custom_U1949' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Endereço\" é obrigatório.'
			)
		),
		'custom_U1941' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"E-mail\" é obrigatório.'
			)
		),
		'custom_U1937' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Pessoa Física/Jurídica',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Pessoa Física/Jurídica\" é obrigatório.'
			)
		),
		'custom_U1954' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Quer ser Voluntário?',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Quer ser Voluntário?\" é obrigatório.'
			)
		),
		'custom_U1945' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Área de atuação',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Área de atuação\" é obrigatório.'
			)
		),
		'custom_U1964' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Foto',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Foto\" é obrigatório.'
			)
		),
		'custom_U1973' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Perfil',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Perfil\" é obrigatório.'
			)
		)
	)
);

process_form($form);
?>
