<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.0.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Criar Evento Formulário envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'fields' => array(
		'custom_U4602' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome do Evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome do Evento\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Local do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Local do evento\" é obrigatório.',
				'format' => 'O campo \"Local do evento\" possui um email inválido.'
			)
		),
		'custom_U4623' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Data do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Data do evento\" é obrigatório.'
			)
		),
		'custom_U4615' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Hora do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Hora do evento\" é obrigatório.'
			)
		),
		'custom_U4610' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Foto do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Foto do evento\" é obrigatório.'
			)
		),
		'custom_U4628' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Valor do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Valor do evento\" é obrigatório.'
			)
		),
		'custom_U4619' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Evento online ou presencial',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Evento online ou presencial\" é obrigatório.'
			)
		),
		'custom_U4638' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Insira redes socias',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Insira redes socias\" é obrigatório.'
			)
		),
		'custom_U4606' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Descrição do evento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Descrição do evento\" é obrigatório.'
			)
		),
		'custom_U4919' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Aceita parceria para o evento',
			'required' => true,
			'optionItems' => array(
				'sim',
				'não'
			),
			'errors' => array(
				'required' => 'O campo \"Aceita parceria para o evento\" é obrigatório.',
				'format' => 'O campo \"Aceita parceria para o evento\" possui um valor inválido.'
			)
		)
	)
);

process_form($form);
?>
